### ISSUE TITLE
Allow futureTechFog to be configured

### ISSUE THREAD

**Issue by mileswest07** [7yl4r/techtreejs#22]
Allow a developer to customize the "aesthetic" or a/several "custom" fog type(s) using JS configurations or CSS classes. 
Potential fix would modify techtree.js lines 166 and 167 (chunk at 157 - 168).

**Comment by 7yl4r** [comment]
I think you're absolutely right about using classes here. Hopefully the various styles ("shown", "hidden", "dummy" (#16)) can be pulled out into css.

**Comment by 7yl4r** [comment]
This will be implemented via #18
